## Habilitar el plugin de management para UI y API REST
## Las colas son declaradas automáticamente por los servicios al conectarse

log.console = true
log.console.level = info
management.load_definitions = /etc/rabbitmq/definitions.json
