version: '3.8'

services:
  db-reservations:
    build:
      context: ./src/docker
    container_name: db-reservations
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: filmstars_reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: